const UserActionTypes ={
    GOOGLE_SIGN_IN_START : 'GOOGLE_SIGN_IN_START',
    SIGN_IN_SUCCESS : 'SIGN_IN_SUCCESS',
    SIGN_IN_FAILURE : 'SIGN_IN_FAILURE',
    EMAIL_SIGN_IN_START : 'EMAIL_SIGN_IN_START',
    SET_CURRENT_USER : 'SET_CURRENT_USER',
    CHECK_USER_SESSION: 'CHECK_USER_SESSION' ,
    SIGN_OUT_USER_SUCCESS: 'SIGN_OUT_USER_SUCCESS',
    SIGN_OUT_USER_FAILURE: 'SIGN_OUT_USER_FAILURE',
    SIGN_OUT_USER_START: 'SIGN_OUT_USER_START',
    SIGN_UP_WITH_EMAIL_START : 'SIGN_UP_WITH_EMAIL_START',
    SIGN_UP_WITH_EMAIL_SUCCESS : 'SIGN_UP_WITH_EMAIL_SUCCESS',
    SIGN_UP_WITH_EMAIL_FAILURE: 'SIGN_UP_WITH_EMAIL_FAILURE',
    ADD_CONTACT : 'ADD_CONTACT',
    FETCH_CONTACTS: 'FETCH_CONTACTS',
    LOAD_CONTACTS_TO_STATE: 'LOAD_CONTACTS_TO_STATE',
    DELETE_CONTACT: 'DELETE_CONTACT'
}
export default UserActionTypes;